CREATE TABLE BRANDS
(
    BRAND_ID   INT PRIMARY KEY,
    BRAND_NAME VARCHAR(255) NOT NULL
);
CREATE TABLE PRICES
(
    PRICE_ID   INT PRIMARY KEY AUTO_INCREMENT,
    BRAND_ID   INT,
    START_DATE TIMESTAMP,
    END_DATE   TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID INT,
    PRIORITY   INT,
    PRICE      DECIMAL(10, 2),
    CURRENCY   VARCHAR(3),
    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS (BRAND_ID)
);
